### ISSUE TITLE
CPU and Memory setting

### ISSUE THREAD

**Issue by premal** [sheepkiller/presto-marathon-docker#4]
Not really an issue, but a question. What is the logic behind setting cpu = 2 and memory = 2G for the worker nodes?

**Comment by sheepkiller** [comment]
Development was made on VMs with 4 vCPUs and 6GB of RAM, so those default settings.
Please note that presto has changed and you need at least 4GB of RAM for workers (2GB are allocated by default for internal use). Current version I use to deal with it is unsatisfactory and I hope to release an update soon to address those issues
